[RFC] Improve long parameter, argument, and element list organization
willowtreeapps/swift-style-guide pull request #38
Opened 2017-05-03 18:40 UTC by willtellis

I think these coding style changes improve organization and readability for long function parameter lists, long function argument lists, and long collection element lists. I don't think these style changes should be mandatory, but they ought to be part of the suggested style. They are especially helpful for complex view model declarations, as I think my example shows. If you agree, please help me improve the language and examples.

2017-05-03 18:41 UTC, hpwooten commented on README.markdown
> +        )
If you also put a comma after this one, then your diffs don't have an extra line when you add to an array.

2017-05-03 18:42 UTC, hpwooten commented on README.markdown
> +) -> Bool {
I really like this style. I go so far as to put everything on it's own line as soon as it becomes longer than one line. That usually translates to three parameters.

2017-05-03 19:01 UTC, ianterrell commented
I'm somewhat in favor, but halfway opposed.

I think that vertical real estate implies importance and complexity, and this style gives the appearance of complexity for what is often trivial code (initialization, method calls). I am more in favor of spreading these types of calls across many lines at the call site when parameters are non-trivial (e.g. involve computation), and less in favor of it when they're simple (e.g. constants). 

Compare, for instance, the suggested preferred struct init with my preferred style for that example:

```swift
let foo = CellViewModel(title: "Foo", detail: "Reticulated", showDisclosureIndicator: true)
let bar = CellViewModel(title: "Bar",detail: "Unreticulated", showDisclosureIndicator: false)
let secondSection = SectionViewModel(title: "Splines", dataSource: [foo, bar])
```

We've gone from 15 lines to 3. I don't think creating a little data is 15 lines of important.

To generalize it, you risk code like this:

```
simple
simple
simple
simple
simple
simple

complex
complex
complex

simple
simple
simple
simple
```

Which I would find less readable at a glance, as the "meat" is obscured.

2017-05-03 19:08 UTC, ianterrell commented
That said, I do this for method declarations, especially with generics or other line-bloating things. Here's an example from live code:

```swift
    private func getData<T: ResultBasedDocument>(
        _ request: URLRequest,
        cacheFile: FileWriter?,
        parser: XMLPushParser<T>,
        completion: @escaping (Result<T.Result, MetadataFetchError>) -> Void
    ) -> Cancellable {
        ...
    }
```

2017-05-05 14:52 UTC, willtellis commented
@ianterrell I get what you're saying about the implied importance of vertical real estate. I've been dealing with a lot of declarative code, and I think that's where this style can be used to increase clarity, as opposed to more imperative or algorithmic code. Much like JSON or HTML, the structure of the data _is_ the complex part of the code. At the risk of undermining my toy example, I think I would actually write that bit of code like so:
```
let firstSection = SectionViewModel(
    title: "Splines",
    dataSource: [
        CellViewModel(title: "Foo", detail: "Reticulated", showDisclosureIndicator: true),
        CellViewModel(title: "Bar", detail: "Unreticulated", showDisclosureIndicator: false)
    ]
)
```
The point being that the hierarchical structure of the SectionViewModel and its relationship to the CellViewModels are made more apparent by the nested declaration, which itself is made clearer by the vertical and horizontal spacing I'm proposing. In more algorithmic/imperative code, declaring the objects before the place where they're used makes more sense. Doing so reduces nesting, so you may not need to use this kind of spacing.

2017-05-05 14:59 UTC, willtellis commented
Ultimately, I'm really just proposing a consistent, generalizable way to break things up across multiple lines when it's necessary to improve clarity. In any particular case, refactoring the code may be a better solution, but prescribing a strategy for breaking up long lines should not imply the preclusion of that option.

2017-05-05 15:10 UTC, willtellis commented on README.markdown
> +        )
True, though I can go either way on making that part of the style. I wish trailing commas were also available for function parameters/arguments for the sake of consistency when using this code organization strategy.

2017-05-05 15:18 UTC, ianterrell commented on README.markdown
> +        )
It's also a separate issue from this request. Trailing commas where possible are mandatory in my opinion though. :) You [will not see it for argument lists](https://github.com/apple/swift-evolution/blob/master/proposals/0084-trailing-commas.md) though.

2019-09-17 13:59 UTC, ianterrell reviewed
Reviewing in order to remove from my "To Review" report in GitHub.

2019-10-30 20:51 UTC, ianterrell requested changes
I don't want to be on this PR anymore. :)

2019-10-31 16:45 UTC, closed without merging